### ISSUE TITLE
new tag requested

### ISSUE THREAD

**Issue by RalphAS** [fhs/ZipFile.jl#41]
Please tag a current revision; the last tag segfaults for some of us on Julia v0.7, whereas current master seems to run well and passes the package test suite on a recent Julia nightly. This will help other packages depending on this one.

**Comment by SimonDanisch** [comment]
I just see, that there doesn't seem attobot installed, and I only seem to have enought rights to create a tag.
@fhs, could we install attobot? 
https://github.com/apps/attobot/installations/new

**Comment by fhs** [comment]
@SimonDanisch attobot is installed.
