### ISSUE TITLE
Where'd the docs go?

### ISSUE THREAD

**Issue by Jacob-Stevens-Haas** [fhs/ZipFile.jl#45]
Hey, I'm hoping to unzip a file using Julia, but I see that the documentation at https://zipfilejl.readthedocs.io/en/latest/ was removed from the README.md, and that the listed website is empty.  How do we use zipfile?

**Comment by fhs** [comment]
Use the builtin help in Julia:
```
julia> import ZipFile

help?> ZipFile   # type ?ZipFile
search: ZipFile

  A Julia package for reading/writing ZIP archive files
...

help?> ZipFile.Reader
  Reader represents a ZIP file open for reading.
...
```
The readthedocs site was a hack I came up with when Julia didn't have docstrings.
