### ISSUE TITLE
ZIP64 is not supported (can't read more than 65535 files)

### ISSUE THREAD

**Issue by quatrejuin** [fhs/ZipFile.jl#56]
Can only read not more than 65535 files.

**Comment by fhs** [comment]
Yes, [ZIP64](https://en.wikipedia.org/wiki/Zip_(file_format)#ZIP64) support is not implemented. There is a stalled PR (https://github.com/fhs/ZipFile.jl/pull/28) that added ZIP64 read support. I would be grateful is someone continued the work.
